apiVersion: apps/v1
kind: Deployment
metadata:
    name: stt-svc
spec:
    selector:
      matchLabels:
        app: stt-svc
    template:
      metadata:
        labels:
          app: stt-svc
      spec:
        containers:
        - name: stt
          image: ecosystem/stt
          ports:
          - containerPort: 43007
        env:
        - name: WHISPER_DEVICE_TYPE
          value: "cpu"
        - name: WHISPER_MODEL
          value: "tiny"
